### ISSUE TITLE
call not recoreded only recored in some kb noting is in it

### ISSUE THREAD

**Issue by ApiXDoc** [Ammar-Ishfaq/CallRecording#3]
call not recoreded only recored in some kb noting is in it

**Comment by Ammar-Ishfaq** [comment]
could you share the device info?
Device name: 
Os Version:

**Comment by ApiXDoc** [comment]
thanks bro to reply its android 12 mi9 prime

**Comment by Ammar-Ishfaq** [comment]
Due to system limitations, the repository description clearly specifies that it is compatible only with Android Oreo (8.0) and not with later versions.
