### ISSUE TITLE
Not working in Android 11

### ISSUE THREAD

**Issue by ashwinikmr048** [Ammar-Ishfaq/CallRecording#4]

**Comment by Ammar-Ishfaq** [comment]
Due to system limitations, the repository description clearly specifies that it is compatible only with Android Oreo (8.0) and not with later versions.

**Comment by ashwinikmr048** [comment]
Any more option are there so that call recording supports on android 11 and
above?

**Comment by Ammar-Ishfaq** [comment]
For now, it looks like only one way that your device must be rooted to achieve that.
**Danger Disclaimer**: 
- Rooting can cause your phone damage. i.e.: software brick, etc.
- Not Suggesting to root your device
- This repo will not work on that as well (this is built by keeping in mind android-8)

**Comment by ashwinikmr048** [comment]
Hi One request can you please check if the below app works in your country or not??

https://play.google.com/store/apps/details?id=com.automaticcallrecorder.autorecordphonecalls

**Comment by fukemy** [comment]
any solution for android 14?
